In [12]:
import os
import pandas as pd
import numpy as np

In [13]:
import tensorflow as tf

In [14]:
os.listdir()

['.ipynb_checkpoints',
 'Diabetic_Retinopathy_Challenge',
 'DR model-Copy1.ipynb',
 'DR model.ipynb',
 'kernel.ipynb',
 'resized',
 'resized.zip',
 'resizedds.zip',
 'resizedds_1024.zip',
 'resizedds_2000.zip',
 'train.zip',
 'train.zip.002',
 'trainLabels.csv',
 'trainLabels.csv.zip']

In [15]:
images = os.listdir()[3]

In [16]:
train_labels = pd.read_csv('trainLabels.csv')

In [17]:
train_labels.head()

image  level
0   10_left      0
1  10_right      0
2   13_left      0
3  13_right      0
4   15_left      1

In [18]:
np.size(os.listdir("./resized/"))

1000

In [31]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image

In [32]:
rows,cols = 224,224

In [33]:
immatrix = []
imlabels = []

In [34]:
for file in os.listdir("./resized/"):
    base = os.path.basename("./resized/" + file)
    print(file)
    fileName = os.path.splitext(base)[0]
    imlabels.append(train_labels.loc[train_labels.image==fileName, 'level'].values[0])
    im = Image.open("./resized/" + file)
    img = im.resize((rows,cols))
    immatrix.append(np.array(img))

1000_left.jpeg
1000_right.jpeg
1002_left.jpeg
1002_right.jpeg
1008_left.jpeg
1008_right.jpeg
100_left.jpeg
100_right.jpeg
1011_left.jpeg
1011_right.jpeg
1012_left.jpeg
1012_right.jpeg
1017_left.jpeg
1017_right.jpeg
1020_left.jpeg
1020_right.jpeg
1021_left.jpeg
1021_right.jpeg
1024_left.jpeg
1024_right.jpeg
1027_left.jpeg
1027_right.jpeg
1029_left.jpeg
1029_right.jpeg
102_left.jpeg
102_right.jpeg
1030_left.jpeg
1030_right.jpeg
1032_left.jpeg
1032_right.jpeg
1034_left.jpeg
1034_right.jpeg
1035_left.jpeg
1035_right.jpeg
1036_left.jpeg
1036_right.jpeg
1037_left.jpeg
1037_right.jpeg
1040_left.jpeg
1040_right.jpeg
1041_left.jpeg
1041_right.jpeg
1042_left.jpeg
1042_right.jpeg
1043_left.jpeg
1043_right.jpeg
1044_left.jpeg
1044_right.jpeg
1047_left.jpeg
1047_right.jpeg
1049_left.jpeg
1049_right.jpeg
104_left.jpeg
104_right.jpeg
1050_left.jpeg
1050_right.jpeg
1051_left.jpeg
1051_right.jpeg
1052_left.jpeg
1052_right.jpeg
1055_left.jpeg
1055_right.jpeg
1056_left.jpeg
1056_right.jpeg
1057_left.jpeg

497_left.jpeg
497_right.jpeg
498_left.jpeg
498_right.jpeg
49_left.jpeg
49_right.jpeg
502_left.jpeg
502_right.jpeg
505_left.jpeg
505_right.jpeg
508_left.jpeg
508_right.jpeg
509_left.jpeg
509_right.jpeg
510_left.jpeg
510_right.jpeg
511_left.jpeg
511_right.jpeg
513_left.jpeg
513_right.jpeg
517_left.jpeg
517_right.jpeg
51_left.jpeg
51_right.jpeg
525_left.jpeg
525_right.jpeg
527_left.jpeg
527_right.jpeg
528_left.jpeg
528_right.jpeg
52_left.jpeg
52_right.jpeg
531_left.jpeg
531_right.jpeg
532_left.jpeg
532_right.jpeg
534_left.jpeg
534_right.jpeg
54_left.jpeg
54_right.jpeg
551_left.jpeg
551_right.jpeg
554_left.jpeg
554_right.jpeg
556_left.jpeg
556_right.jpeg
557_left.jpeg
557_right.jpeg
558_left.jpeg
558_right.jpeg
560_left.jpeg
560_right.jpeg
563_left.jpeg
563_right.jpeg
566_left.jpeg
566_right.jpeg
568_left.jpeg
568_right.jpeg
56_left.jpeg
56_right.jpeg
575_left.jpeg
575_right.jpeg
579_left.jpeg
579_right.jpeg
57_left.jpeg
57_right.jpeg
58_left.jpeg
58_right.jpeg
596_left.jpeg
596_right.jpeg

In [35]:
immatrix = np.asarray(immatrix)
imlabels = np.asarray(imlabels)

In [36]:
immatrix[0].shape

(224, 224, 3)

In [37]:
imlabels[1].shape

()

In [38]:
from sklearn.utils import shuffle

data,Label = shuffle(immatrix,imlabels, random_state=2)
train_data = [data,Label]
type(train_data)

list

In [39]:
(X,y) = (train_data[0],train_data[1])

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

print(X_train.shape)
print(X_test.shape)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

#Normalizing Data Between [0,1]
X_train /= 255
X_test /= 255

print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

(800, 224, 224, 3)
(200, 224, 224, 3)
X_train shape: (800, 224, 224, 3)
800 train samples
200 test samples


In [43]:
y_train

array([2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 4, 2, 2, 0, 0, 0, 0, 0, 1, 0,
       2, 0, 4, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 2, 0, 0, 3, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 4, 0, 2, 2, 0, 0, 1, 0, 4, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 2, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2,
       2, 0, 4, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 2, 0, 0, 0, 1, 3, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 3, 0,
       0, 0, 2, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2,
       0, 1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 2, 0, 0,
       0, 0, 0, 2, 0, 4, 0, 0, 0, 0, 4, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2,
       2, 3, 0, 2, 0, 0, 0, 2, 0, 1, 0, 4, 3, 2, 0,

In [44]:
X_train[0].shape

(224, 224, 3)

In [45]:
from keras.utils import np_utils

n_classes = 5

Y_train = np_utils.to_categorical(y_train, n_classes)
Y_test = np_utils.to_categorical(y_test, n_classes)

In [46]:
Y_train[0]

array([0., 0., 1., 0., 0.], dtype=float32)

In [59]:
from keras.applications.vgg16 import VGG16
base_model = VGG16(weights='imagenet',include_top=False, input_shape=(224,224,3))
print(base_model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [60]:
from keras.models import Sequential
from keras.layers import Dense , Flatten , Dropout, Activation

top_model = Sequential()
top_model.add(Flatten(input_shape=base_model.output_shape[1:]))
top_model.add(Dense(256, activation='relu'))
top_model.add(Dropout(0.5))
top_model.add(Dense(5, activation='softmax'))

In [61]:
from keras.models import Model

model=Model(inputs=base_model.input, outputs=top_model(base_model.output))

In [62]:
from keras import optimizers

model.compile(loss='categorical_crossentropy',
     optimizer=optimizers.SGD(lr=1e-4, momentum=0.9),
     metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [63]:
batch_size =32
n_epochs =20
n_batches = 1000//batch_size

In [64]:
with tf.device("/gpu:0"):
    model.fit(x = X_train,y=Y_train)

Epoch 1/1
800/800 [==============================] - 40s 51ms/step - loss: 1.3335 - acc: 0.6412


In [66]:
with tf.device("/gpu:0"):
    probs = model.predict(X_test)

In [67]:
probs

array([[0.7469161 , 0.12697235, 0.09609537, 0.01520797, 0.01480818],
       [0.74539506, 0.12905595, 0.09546444, 0.01587664, 0.01420796],
       [0.76456404, 0.10236968, 0.0993899 , 0.01335068, 0.02032567],
       [0.77921134, 0.11456709, 0.07576527, 0.01564741, 0.01480898],
       [0.7887618 , 0.08495997, 0.09623443, 0.01516435, 0.01487946],
       [0.8529148 , 0.06306431, 0.06123783, 0.01182197, 0.01096097],
       [0.7030872 , 0.151342  , 0.11497149, 0.01424445, 0.01635478],
       [0.81753784, 0.08296345, 0.07185599, 0.01240215, 0.01524054],
       [0.7881633 , 0.09797374, 0.08357528, 0.01381798, 0.01646966],
       [0.78064144, 0.10834687, 0.07987257, 0.0136588 , 0.0174803 ],
       [0.8137065 , 0.07654356, 0.08101342, 0.01341571, 0.01532075],
       [0.73984075, 0.13584597, 0.0946652 , 0.014114  , 0.01553399],
       [0.7456063 , 0.12410536, 0.10050822, 0.01492799, 0.01485199],
       [0.792919  , 0.09453233, 0.08389606, 0.01589908, 0.01275349],
       [0.8109509 , 0.07828525, 0.

In [69]:
Y_test

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0.